# Generated by Django 5.2 on 2025-04-07 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundraising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('category', models.CharField(max_length=255, verbose_name='Категорії')),
                ('description', models.TextField(max_length=2000, verbose_name='Description')),
                ('main_image', models.ImageField(upload_to='static/pictures/fundraising_images/', verbose_name='Зображення кампанії')),
                ('needed_sum', models.FloatField(verbose_name='Цільова сума (₴)')),
                ('start_date', models.FloatField(verbose_name='Дата початку')),
                ('end_date', models.FloatField(verbose_name='Дата завершення')),
                ('link_for_money', models.TextField(max_length=2000, verbose_name='Реквізити для переказу')),
                ('report', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Звіт по завершенню збору')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundraisings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
