# Generated by Django 5.1.7 on 2025-04-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundraising',
            name='current_sum',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundraising',
            name='link_for_money',
            field=models.TextField(blank=True, default='Реквізити будуть додані пізніше', max_length=2000, verbose_name='Реквізити для переказу'),
        ),
        migrations.AddField(
            model_name='fundraising',
            name='report',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Звіт по завершенню збору'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='fundraising',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='fundraising',
            name='end_date',
            field=models.DateField(verbose_name='Дата завершення'),
        ),
        migrations.AlterField(
            model_name='fundraising',
            name='main_image',
            field=models.ImageField(upload_to='fundraising_images/', verbose_name='Зображення кампанії'),
        ),
        migrations.AlterField(
            model_name='fundraising',
            name='needed_sum',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цільова сума (₴)'),
        ),
        migrations.AlterField(
            model_name='fundraising',
            name='start_date',
            field=models.DateField(verbose_name='Дата початку'),
        ),
        migrations.AlterField(
            model_name='fundraising',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
