# Generated by Django 5.2 on 2025-04-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraising',
            name='end_date',
            field=models.DateField(verbose_name='Дата завершення'),
        ),
        migrations.AlterField(
            model_name='fundraising',
            name='main_image',
            field=models.ImageField(upload_to='fundraising_images/', verbose_name='Зображення кампанії'),
        ),
        migrations.AlterField(
            model_name='fundraising',
            name='needed_sum',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цільова сума (₴)'),
        ),
        migrations.AlterField(
            model_name='fundraising',
            name='start_date',
            field=models.DateField(verbose_name='Дата початку'),
        ),
    ]
