# Generated by Django 5.1.7 on 2025-04-14 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisings', '0002_add_donation_model'),
        ('fundraisings', '0002_donation'),
    ]

    operations = [
    ]
