# Generated by Django 5.1.7 on 2025-04-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisings', '0003_merge_0002_add_donation_model_0002_donation'),
        ('fundraisings', 'add_status_field'),
    ]

    operations = [
    ]
