# Generated by Django 5.2 on 2025-04-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisings', '0003_category_alter_fundraising_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraising',
            name='category',
            field=models.CharField(max_length=255, verbose_name='Категорії'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
