# Generated by Django 5.2 on 2025-04-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisings', '0005_category_alter_fundraising_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundraising',
            name='category',
        ),
        migrations.AddField(
            model_name='fundraising',
            name='categories',
            field=models.ManyToManyField(related_name='fundraisings', to='fundraisings.category'),
        ),
    ]
