# Generated by Django 5.1.7 on 2025-04-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisings', '0006_ensure_primary_category'),
        ('fundraisings', '0007_add_status_field'),
    ]

    operations = [
    ]
