# Generated by Django 5.1.7 on 2025-04-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisings', '0008_merge_20250414_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraising',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='associated_fundraisings', to='fundraisings.category'),
        ),
    ]
