# Generated by Django 5.1.7 on 2025-04-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisings', '0002_ensure_default_categories'),
        ('fundraisings', '0009_alter_fundraising_categories'),
    ]

    operations = [
    ]
