# Generated by Django 5.1.7 on 2025-04-14 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_add_user_statistics'),
        ('authentication', '0002_user_statistics'),
    ]

    operations = [
    ]
