# Generated by Django 5.1.7 on 2025-04-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_merge_0002_add_user_statistics_0002_user_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Банер профілю'),
        ),
    ]
