# Generated by Django 5.1.7 on 2025-04-15 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='largest_donation_amount',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='supported_fundraisings_count',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='total_donated_amount',
        ),
    ]
