# Generated by Django 5.1.7 on 2025-04-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_customuser_postal_code_customuser_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='facebook',
            field=models.TextField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='instagram',
            field=models.TextField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram',
            field=models.TextField(blank=True, null=True, verbose_name='Telegram'),
        ),
    ]
