# Generated by Django 5.1.7 on 2025-04-25 22:15

import fundraisings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisings', '0013_reportvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraising',
            name='link_for_money',
            field=models.URLField(default='https://dovir.ua/payment', verbose_name='Посилання для грошей'),
        ),
        migrations.AlterField(
            model_name='fundraising',
            name='main_image',
            field=models.ImageField(null=True, upload_to='fundraisings/%Y/%m/', verbose_name='Головне зображення'),
        ),
        migrations.AlterField(
            model_name='reportimage',
            name='image',
            field=models.ImageField(upload_to=fundraisings.models.Report.report_image_path, verbose_name='Фото звіту'),
        ),
        migrations.AlterField(
            model_name='reportvideo',
            name='video',
            field=models.FileField(upload_to=fundraisings.models.Report.report_video_path, verbose_name='Відео звіту'),
        ),
    ]
