# Generated by Django 5.1.7 on 2025-04-26 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisings', '0010_ensure_categories_after_reset'),
        ('fundraisings', '0014_alter_fundraising_link_for_money_and_more'),
    ]

    operations = [
    ]
