# Generated by Django 5.1.7 on 2025-04-25 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_customuser_largest_donation_amount_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
