# Generated by Django 5.1.7 on 2025-04-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_customuser_categories_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/%Y/%m/', verbose_name='Аватар'),
        ),
    ]
